-- MySQL Script generated by MySQL Workbench
-- 10/19/16 23:46:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `middle_name` VARCHAR(45) NULL COMMENT '',
  `age` VARCHAR(45) NOT NULL COMMENT '',
  `gender` VARCHAR(45) NOT NULL COMMENT '',
  `cell_number` VARCHAR(45) NULL COMMENT '',
  `email_add` VARCHAR(45) NULL COMMENT '',
  `home_add` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `middle_name` VARCHAR(45) NULL COMMENT '',
  `age` VARCHAR(45) NULL COMMENT '',
  `gender` VARCHAR(45) NULL COMMENT '',
  `cell_number` VARCHAR(45) NULL COMMENT '',
  `email_add` VARCHAR(45) NULL COMMENT '',
  `home_add` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `first_name_UNIQUE` (`first_name` ASC)  COMMENT '',
  UNIQUE INDEX `last_name_UNIQUE` (`last_name` ASC)  COMMENT '',
  UNIQUE INDEX `age_UNIQUE` (`age` ASC)  COMMENT '',
  UNIQUE INDEX `gender_UNIQUE` (`gender` ASC)  COMMENT '',
  UNIQUE INDEX `home_add_UNIQUE` (`home_add` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(100) NOT NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `employee_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_course_employee_idx` (`employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_course_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_list` (
  `course_id` INT NOT NULL COMMENT '',
  `course_employee_id` INT NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`course_id`, `course_employee_id`, `student_id`)  COMMENT '',
  INDEX `fk_course_has_student_student1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_course_has_student_course1_idx` (`course_id` ASC, `course_employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_course_has_student_course1`
    FOREIGN KEY (`course_id` , `course_employee_id`)
    REFERENCES `mydb`.`course` (`id` , `employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_has_student_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(100) NOT NULL COMMENT '',
  `course_id` INT NOT NULL COMMENT '',
  `course_employee_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `course_id`, `course_employee_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_task_course1_idx` (`course_id` ASC, `course_employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_task_course1`
    FOREIGN KEY (`course_id` , `course_employee_id`)
    REFERENCES `mydb`.`course` (`id` , `employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ann_calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ann_calendar` (
  `announcement` VARCHAR(45) NOT NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  `task_id` INT NOT NULL COMMENT '',
  `task_course_id` INT NOT NULL COMMENT '',
  `task_course_employee_id` INT NOT NULL COMMENT '',
  INDEX `fk_employee_has_task_employee1_idx` (`employee_id` ASC)  COMMENT '',
  INDEX `fk_ann_calendar_task1_idx` (`task_id` ASC, `task_course_id` ASC, `task_course_employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_employee_has_task_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ann_calendar_task1`
    FOREIGN KEY (`task_id` , `task_course_id` , `task_course_employee_id`)
    REFERENCES `mydb`.`task` (`id` , `course_id` , `course_employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ask` VARCHAR(45) NOT NULL COMMENT '',
  `task_id` INT NOT NULL COMMENT '',
  `task_course_id` INT NOT NULL COMMENT '',
  `task_course_employee_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_question_task1_idx` (`task_id` ASC, `task_course_id` ASC, `task_course_employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_question_task1`
    FOREIGN KEY (`task_id` , `task_course_id` , `task_course_employee_id`)
    REFERENCES `mydb`.`task` (`id` , `course_id` , `course_employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`choice` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `choose` VARCHAR(45) NOT NULL COMMENT '',
  `question_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `question_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_choice_question1_idx` (`question_id` ASC)  COMMENT '',
  CONSTRAINT `fk_choice_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stud_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stud_answer` (
  `choice_id` INT NOT NULL COMMENT '',
  `choice_question_id` INT NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`choice_id`, `choice_question_id`, `student_id`)  COMMENT '',
  INDEX `fk_stud_answer_student1_idx` (`student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_stud_answer_choice1`
    FOREIGN KEY (`choice_id` , `choice_question_id`)
    REFERENCES `mydb`.`choice` (`id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stud_answer_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `time` VARCHAR(45) NULL COMMENT '',
  `date` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attendance` (
  `class_list_course_id` INT NOT NULL COMMENT '',
  `class_list_course_employee_id` INT NOT NULL COMMENT '',
  `class_list_student_id` INT NOT NULL COMMENT '',
  `schedule_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`class_list_course_id`, `class_list_course_employee_id`, `class_list_student_id`, `schedule_id`)  COMMENT '',
  INDEX `fk_class_list_has_schedule_schedule1_idx` (`schedule_id` ASC)  COMMENT '',
  INDEX `fk_class_list_has_schedule_class_list1_idx` (`class_list_course_id` ASC, `class_list_course_employee_id` ASC, `class_list_student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_class_list_has_schedule_class_list1`
    FOREIGN KEY (`class_list_course_id` , `class_list_course_employee_id` , `class_list_student_id`)
    REFERENCES `mydb`.`class_list` (`course_id` , `course_employee_id` , `student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_list_has_schedule_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `mydb`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`result` (
  `choice_id` INT NOT NULL COMMENT '',
  `choice_question_id` INT NOT NULL COMMENT '',
  `stud_answer_choice_id` INT NOT NULL COMMENT '',
  `stud_answer_choice_question_id` INT NOT NULL COMMENT '',
  `stud_answer_student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`choice_id`, `choice_question_id`, `stud_answer_choice_id`, `stud_answer_choice_question_id`, `stud_answer_student_id`)  COMMENT '',
  INDEX `fk_choice_has_stud_answer_choice1_idx` (`choice_id` ASC, `choice_question_id` ASC)  COMMENT '',
  INDEX `fk_result_stud_answer1_idx` (`stud_answer_choice_id` ASC, `stud_answer_choice_question_id` ASC, `stud_answer_student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_choice_has_stud_answer_choice1`
    FOREIGN KEY (`choice_id` , `choice_question_id`)
    REFERENCES `mydb`.`choice` (`id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_stud_answer1`
    FOREIGN KEY (`stud_answer_choice_id` , `stud_answer_choice_question_id` , `stud_answer_student_id`)
    REFERENCES `mydb`.`stud_answer` (`choice_id` , `choice_question_id` , `student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
