-- MySQL Script generated by MySQL Workbench
-- 11/08/16 21:21:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT(11) NOT NULL COMMENT '',
  `username` VARCHAR(255) NULL COMMENT '',
  `auth_key` VARCHAR(32) NULL COMMENT '',
  `password_hash` VARCHAR(255) NULL COMMENT '',
  `password_reset_token` VARCHAR(255) NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `status` SMALLINT(6) NULL COMMENT '',
  `created_at` INT(11) NULL COMMENT '',
  `updated_at` INT(11) NULL COMMENT '',
  `first_name` VARCHAR(30) NOT NULL COMMENT '',
  `middle_name` VARCHAR(30) NULL COMMENT '',
  `last_name` VARCHAR(30) NOT NULL COMMENT '',
  `gender` ENUM('Female', 'Male') NOT NULL COMMENT '',
  `age` VARCHAR(3) NOT NULL COMMENT '',
  `contact_number` VARCHAR(30) NULL COMMENT '',
  `home_add` VARCHAR(255) NOT NULL COMMENT '',
  `employee_type` ENUM('Tutor', 'Admin') NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `created_at_UNIQUE` (`created_at` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(255) NOT NULL COMMENT '',
  `auth_key` VARCHAR(32) NOT NULL COMMENT '',
  `password_hash` VARCHAR(255) NOT NULL COMMENT '',
  `password_reset_token` VARCHAR(255) NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `created_at` INT(11) NOT NULL COMMENT '',
  `status` SMALLINT(6) NOT NULL COMMENT '',
  `updated_at` INT(11) NOT NULL COMMENT '',
  `status_student` ENUM('reserved', 'enrolled', 'done', 'cancelled') NOT NULL COMMENT '',
  `number_of_hours` INT NULL COMMENT '',
  `review_class` ENUM('Senior High / College Entrance Review', 'High School Entrance Test / Science High School Review', 'Civil Service Exam Review', 'Law Aptitude Exam / Law School Admission Test Review', 'National Medical Admission Test Review') NOT NULL COMMENT '',
  `first_name` VARCHAR(30) NOT NULL COMMENT '',
  `middle_name` VARCHAR(30) NULL COMMENT '',
  `guardian_email_address` VARCHAR(255) NULL COMMENT '',
  `last_name` VARCHAR(30) NOT NULL COMMENT '',
  `nickname` VARCHAR(15) NOT NULL COMMENT '',
  `gender` ENUM('Female', 'Male') NOT NULL COMMENT '',
  `age` VARCHAR(3) NOT NULL COMMENT '',
  `contact_number` VARCHAR(30) NOT NULL COMMENT '',
  `home_address` VARCHAR(255) NOT NULL COMMENT '',
  `school` VARCHAR(100) NOT NULL COMMENT '',
  `school_address` VARCHAR(255) NOT NULL COMMENT '',
  `guardian_name` VARCHAR(100) NULL COMMENT '',
  `relation` VARCHAR(45) NULL COMMENT '',
  `guardian_contact_number` VARCHAR(30) NULL COMMENT '',
  `date_of_registration` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `course_description` VARCHAR(200) NULL COMMENT '',
  `time_created` TIME(6) NULL COMMENT '',
  `date_created` DATE NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `employee_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_course_employee_idx` (`employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_course_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_list` (
  `course_id` INT NOT NULL COMMENT '',
  `course_employee_id` INT NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`course_id`, `course_employee_id`, `user_id`)  COMMENT '',
  INDEX `fk_course_has_student_course1_idx` (`course_id` ASC, `course_employee_id` ASC)  COMMENT '',
  INDEX `fk_class_list_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_course_has_student_course1`
    FOREIGN KEY (`course_id` , `course_employee_id`)
    REFERENCES `mydb`.`course` (`id` , `employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_list_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(100) NOT NULL COMMENT '',
  `description` VARCHAR(200) NULL COMMENT '',
  `task_type` ENUM('Exam', 'Quiz', 'Exercise', 'Assignment') NULL COMMENT '',
  `created` TIMESTAMP(6) NULL COMMENT '',
  `time_open` TIME(6) NULL COMMENT '',
  `time_close` TIME(6) NULL COMMENT '',
  `date_open` DATE NULL COMMENT '',
  `date_close` DATE NULL COMMENT '',
  `time_remaining` TIME(6) NULL COMMENT '',
  `attempts` INT NULL COMMENT '',
  `course_id` INT NOT NULL COMMENT '',
  `course_employee_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_task_course1_idx` (`course_id` ASC, `course_employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_task_course1`
    FOREIGN KEY (`course_id` , `course_employee_id`)
    REFERENCES `mydb`.`course` (`id` , `employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ann_calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ann_calendar` (
  `id` INT NOT NULL COMMENT '',
  `announcement` VARCHAR(50) NOT NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  `task_id` INT NOT NULL COMMENT '',
  INDEX `fk_employee_has_task_employee1_idx` (`employee_id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_ann_calendar_task1_idx` (`task_id` ASC)  COMMENT '',
  CONSTRAINT `fk_employee_has_task_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ann_calendar_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ask` VARCHAR(255) NOT NULL COMMENT '',
  `image` VARBINARY(8000) NULL COMMENT '',
  `task_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_question_task1_idx` (`task_id` ASC)  COMMENT '',
  CONSTRAINT `fk_question_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`choice` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `choose` VARCHAR(255) NOT NULL COMMENT '',
  `is_correct` VARCHAR(255) NOT NULL COMMENT '',
  `question_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `question_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_choice_question1_idx` (`question_id` ASC)  COMMENT '',
  CONSTRAINT `fk_choice_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stud_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stud_answer` (
  `choice_id` INT NOT NULL COMMENT '',
  `choice_question_id` INT NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`choice_id`, `choice_question_id`, `user_id`)  COMMENT '',
  INDEX `fk_stud_answer_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_stud_answer_choice1`
    FOREIGN KEY (`choice_id` , `choice_question_id`)
    REFERENCES `mydb`.`choice` (`id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stud_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `subject` VARCHAR(100) NOT NULL COMMENT '',
  `description` VARCHAR(255) NULL COMMENT '',
  `day` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') NOT NULL COMMENT '',
  `schedule` VARCHAR(17) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attendance` (
  `status` ENUM('Absent', 'Late', 'Excuse', 'Present') NOT NULL COMMENT '',
  `class_list_course_id` INT NOT NULL COMMENT '',
  `class_list_course_employee_id` INT NOT NULL COMMENT '',
  `class_list_user_id` INT(11) NOT NULL COMMENT '',
  `schedule_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`class_list_course_id`, `class_list_course_employee_id`, `class_list_user_id`, `schedule_id`)  COMMENT '',
  INDEX `fk_attendance_schedule1_idx` (`schedule_id` ASC)  COMMENT '',
  CONSTRAINT `fk_attendance_class_list1`
    FOREIGN KEY (`class_list_course_id` , `class_list_course_employee_id` , `class_list_user_id`)
    REFERENCES `mydb`.`class_list` (`course_id` , `course_employee_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `mydb`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`result` (
  `feedback` VARCHAR(255) NOT NULL COMMENT '',
  `score` INT NOT NULL COMMENT '',
  `grade` INT NOT NULL COMMENT '',
  `min_grade` INT NULL COMMENT '',
  `max_grade` INT NULL COMMENT '',
  `stud_answer_choice_id` INT NOT NULL COMMENT '',
  `stud_answer_choice_question_id` INT NOT NULL COMMENT '',
  `stud_answer_user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`feedback`)  COMMENT '',
  INDEX `fk_result_stud_answer1_idx` (`stud_answer_choice_id` ASC, `stud_answer_choice_question_id` ASC, `stud_answer_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_result_stud_answer1`
    FOREIGN KEY (`stud_answer_choice_id` , `stud_answer_choice_question_id` , `stud_answer_user_id`)
    REFERENCES `mydb`.`stud_answer` (`choice_id` , `choice_question_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
