-- MySQL Script generated by MySQL Workbench
-- 08/03/16 23:24:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lsc_lms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lsc_lms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lsc_lms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lsc_lms` ;

-- -----------------------------------------------------
-- Table `lsc_lms`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsc_lms`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(15) NOT NULL COMMENT '',
  `password` VARCHAR(20) NOT NULL COMMENT '',
  `lastname` VARCHAR(30) NOT NULL COMMENT '',
  `firstname` VARCHAR(30) NOT NULL COMMENT '',
  `middlename` VARCHAR(30) NULL COMMENT '',
  `nickname` VARCHAR(15) NOT NULL COMMENT '',
  `gander` VARCHAR(7) NOT NULL COMMENT '',
  `age` INT NOT NULL COMMENT '',
  `email_address` VARCHAR(45) NULL COMMENT '',
  `contact_number` INT NOT NULL COMMENT '',
  `address` VARCHAR(50) NOT NULL COMMENT '',
  `school` VARCHAR(45) NOT NULL COMMENT '',
  `school_address` VARCHAR(50) NOT NULL COMMENT '',
  `guardian_name` VARCHAR(40) NOT NULL COMMENT '',
  `date_of_registration` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `student_username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsc_lms`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsc_lms`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `course_name` VARCHAR(200) NOT NULL COMMENT '',
  `subject` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsc_lms`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsc_lms`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `day` VARCHAR(10) NOT NULL COMMENT '',
  `time` VARCHAR(45) NOT NULL COMMENT '',
  `subject` VARCHAR(45) NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  `course_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `student_id`, `course_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_schedule_student_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_schedule_course1_idx` (`course_id` ASC)  COMMENT '',
  CONSTRAINT `fk_schedule_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `lsc_lms`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `lsc_lms`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsc_lms`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsc_lms`.`grade` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NULL COMMENT '',
  `subject` VARCHAR(200) NOT NULL COMMENT '',
  `homework` INT NULL COMMENT '',
  `exercise` INT NULL COMMENT '',
  `quiz` INT NULL COMMENT '',
  `grade_final` INT NULL COMMENT '',
  `attendance` VARCHAR(7) NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  `course_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `student_id`, `course_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_grade_student1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_grade_course1_idx` (`course_id` ASC)  COMMENT '',
  CONSTRAINT `fk_grade_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `lsc_lms`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grade_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `lsc_lms`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsc_lms`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsc_lms`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `category` VARCHAR(45) NULL COMMENT '',
  `course_id` INT NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `course_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_task_course1_idx` (`course_id` ASC)  COMMENT '',
  INDEX `fk_task_student1_idx` (`student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_task_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `lsc_lms`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `lsc_lms`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsc_lms`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsc_lms`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(15) NOT NULL COMMENT '',
  `password` VARCHAR(20) NOT NULL COMMENT '',
  `lastname` VARCHAR(30) NOT NULL COMMENT '',
  `employee_position` VARCHAR(10) NOT NULL COMMENT '',
  `firstname` VARCHAR(30) NOT NULL COMMENT '',
  `middlename` VARCHAR(30) NULL COMMENT '',
  `gender` VARCHAR(7) NOT NULL COMMENT '',
  `age` INT NOT NULL COMMENT '',
  `contact_number` INT NOT NULL COMMENT '',
  `email_address` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsc_lms`.`employee_submits_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsc_lms`.`employee_submits_grade` (
  `employee_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `grade_id` INT NOT NULL COMMENT '',
  `grade_student_id` INT NOT NULL COMMENT '',
  `grade_course_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`employee_id`, `grade_id`, `grade_student_id`, `grade_course_id`)  COMMENT '',
  INDEX `fk_employee_has_grade_grade1_idx` (`grade_id` ASC, `grade_student_id` ASC, `grade_course_id` ASC)  COMMENT '',
  INDEX `fk_employee_has_grade_employee1_idx` (`employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_employee_has_grade_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `lsc_lms`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_grade_grade1`
    FOREIGN KEY (`grade_id` , `grade_student_id` , `grade_course_id`)
    REFERENCES `lsc_lms`.`grade` (`id` , `student_id` , `course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsc_lms`.`employee_creates_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsc_lms`.`employee_creates_course` (
  `employee_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `course_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`employee_id`, `course_id`)  COMMENT '',
  INDEX `fk_employee_has_course_course1_idx` (`course_id` ASC)  COMMENT '',
  INDEX `fk_employee_has_course_employee1_idx` (`employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_employee_has_course_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `lsc_lms`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_course_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `lsc_lms`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
